ktor:
  deployment:
    port: 8081
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.BDDKt.configureDatabase
      - com.example.RoutingKt.configureRouting

db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}